# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sangmile Blog
email: starscar0208@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello. This is Sangmin Kim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sangmile.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sangmile
github_username: sangmile
favicon: /favicon.png

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: sangmile

# Build settings
# theme: minima
remote_theme: chrisrhymes/bulma-clean-theme
# plugins:
#   - github-pages

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Sangmin Kim"
      layout: post
      hero_image: /assets/images/background.png
      show_sidebar: true
  - scope:
      path: ""
      type: "daily"
    values:
      layout: page
      show_sidebar: true
  # - scope:
  #     path: ""
  # - scope:
  #     path: ""
  #     type: "pages"
  #   values:
  #     show_sidebar: true

collections:
  daily:
    output: true
    layout: daily
    permalink: /daily/:path/
  # themes:
  #   output: true
  #   permalink: /jekyll-themes/:path/
